// sample-data.ts
import { dataTableTypes } from "./data-table-types";

export const sampleData: dataTableTypes[] = [
  {
    id: 0,
    fullname: "John Doe",
    role: "admin",
    username: "jdoe",
    status: "active",
  },
  {
    id: 1,
    fullname: "Jane Smith",
    role: "dealer",
    username: "jsmith",
    status: "inactive",
  },
  {
    id: 2,
    fullname: "Alice Johnson",
    role: "customer",
    username: "alicej",
    status: "active",
  },
  {
    id: 3,
    fullname: "Bob Brown",
    role: "dealer",
    username: "bobb",
    status: "inactive",
  },
  {
    id: 4,
    fullname: "Charlie Davis",
    role: "admin",
    username: "cdavis",
    status: "active",
  },
  {
    id: 5,
    fullname: "Diana Evans",
    role: "customer",
    username: "devans",
    status: "inactive",
  },
  {
    id: 6,
    fullname: "Edward Harris",
    role: "dealer",
    username: "eharris",
    status: "active",
  },
  {
    id: 7,
    fullname: "Fiona Green",
    role: "customer",
    username: "fgreen",
    status: "inactive",
  },
  {
    id: 8,
    fullname: "George Hill",
    role: "admin",
    username: "ghill",
    status: "active",
  },
  {
    id: 9,
    fullname: "Hannah King",
    role: "dealer",
    username: "hking",
    status: "inactive",
  },
  {
    id: 10,
    fullname: "Ian Lee",
    role: "customer",
    username: "ilee",
    status: "active",
  },
  {
    id: 11,
    fullname: "Jack Martin",
    role: "admin",
    username: "jmartin",
    status: "inactive",
  },
  {
    id: 12,
    fullname: "Karen Nelson",
    role: "dealer",
    username: "knelson",
    status: "active",
  },
  {
    id: 13,
    fullname: "Liam O'Connor",
    role: "customer",
    username: "loconnor",
    status: "inactive",
  },
  {
    id: 14,
    fullname: "Mia Perez",
    role: "admin",
    username: "mperez",
    status: "active",
  },
  {
    id: 15,
    fullname: "Noah Quinn",
    role: "dealer",
    username: "nquinn",
    status: "inactive",
  },
  {
    id: 16,
    fullname: "Olivia Roberts",
    role: "customer",
    username: "oroberts",
    status: "active",
  },
  {
    id: 17,
    fullname: "Paul Scott",
    role: "admin",
    username: "pscott",
    status: "inactive",
  },
  {
    id: 18,
    fullname: "Quinn Taylor",
    role: "dealer",
    username: "qtaylor",
    status: "active",
  },
  {
    id: 19,
    fullname: "Rachel Wilson",
    role: "customer",
    username: "rwilson",
    status: "inactive",
  },
];
